template:
    path: teststack/bucket.yaml

# It shouldn't require any parameters and its only configuration at this point ought to be
# to override the template_bucket_name it would otherwise inherit to prevent circular dependencies
template_bucket_name: !no_value


hooks:
  {% for action in [ 'create', 'update' ] %}
    after_{{action}}:
        - !print_outputs
        - !replace_values
  {% endfor %}

    before_delete:
        - !empty_bucket "BucketName"
